### ISSUE TITLE
docgen error when trying to generate the html file from the postman json file

### ISSUE THREAD

**Issue by zoug86** [thedevsaddam/docgen#60]
I tried running this on a windows machine:
docgen build -i dc.postman-collection.json -o ~/Downloads/index.html

And I got this error:

'''
fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
←[90m    at fs.js:45:5←[39m
    at req_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\←[4mdocgen-tool←[24m\node_modules\←[4mnatives←[24m\index.js:143:24)
    at Object.req [as require] (C:\Users\Owner\AppData\Roaming\npm\node_modules\←[4mdocgen-tool←[24m\node_modules\←[4mnatives←[24m\index.js:55:10)
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\←[4mdocgen-tool←[24m\node_modules\←[4mgraceful-fs←[24m\fs.js:1:37)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:937:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
'''

Anyone knows how to deal with this?

**Comment by zoug86** [comment]
Issue Solved:
- change the binary file name to docgen.exe
- add the binary file's location to the env path
- cd to the postman json file and run the following command to build your index.html file:
docgen.exe build -i  dc.postman_collection.json -o index.html    (make sure to change the postman json file name to your file name)
